# Generated by Django 5.2.15 on 2026-08-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # db.Project への FK があるため plane.db に依存する。makemigrations が
    # 生成時点の最新（0122）を指しているが、この名前は upstream から消えないので
    # 追従時に壊れることはない。逆にこちらのマイグレーションは spindd_ext 内で
    # 独立して連番を持つため、plane.db 側の 0123 以降と衝突しない
    # （CONTRIBUTING.spindd.md §4）。
    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=64, unique=True, verbose_name='工事番号')),
                ('official_name', models.CharField(blank=True, max_length=255, verbose_name='工事名称')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='発注者')),
                ('site_address', models.CharField(blank=True, max_length=255, verbose_name='工事場所')),
                ('building_use', models.CharField(blank=True, max_length=255, verbose_name='用途')),
                ('structure', models.CharField(blank=True, max_length=255, verbose_name='構造・規模')),
                ('total_floor_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='延床面積（m2）')),
                ('contract_type', models.CharField(choices=[('lump_sum', '総価請負'), ('unit_price', '単価契約'), ('cost_plus_fee', '実費精算')], default='lump_sum', max_length=32, verbose_name='契約形態')),
                ('contract_amount', models.BigIntegerField(blank=True, null=True, verbose_name='請負金額（円）')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='契約日')),
                ('construction_start', models.DateField(blank=True, null=True, verbose_name='着工日')),
                ('construction_end', models.DateField(blank=True, null=True, verbose_name='竣工予定日')),
                ('actual_completion', models.DateField(blank=True, null=True, verbose_name='実竣工日')),
                ('site_agent', models.CharField(blank=True, max_length=255, verbose_name='現場代理人')),
                ('chief_engineer', models.CharField(blank=True, max_length=255, verbose_name='監理技術者・主任技術者')),
                ('remarks', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spindd_construction', to='db.project', verbose_name='現場')),
            ],
            options={
                'verbose_name': '工事情報',
                'verbose_name_plural': '工事情報',
                'db_table': 'spindd_construction_projects',
                'ordering': ('contract_number',),
            },
        ),
    ]
